### ISSUE TITLE
代码报错

### ISSUE THREAD

**Issue by zhoukaiwei66** [AI-confused/CGEC-with-Pointer-Generator-Network-Bart#2]
您好，我在跑您的PGN网络用于纠错的时候，在定义mode的时候`p_gen_input = torch.cat((ht_hat, d_output, self.bart.shared(decoder_input)), -1) `该行代码报错，报错内容如下：`RuntimeError: Sizes of tensors must match except in dimension 1. Got 131 and 1 (The offending index is 0)`，请问您这边遇到过么，感谢。

**Comment by AI-confused** [comment]
因该是torch.cat的这几个tensor在第一个维度不匹配，可以再debug下这几个tensor的size

**Comment by zhoukaiwei66** [comment]
> 因该是torch.cat的这几个tensor在第一个维度不匹配，可以再debug下这几个tensor的size

感谢，搞定了，很奇怪，transformer版本升级一下就可以了，感谢，从您的纠错项目中学到很多
