### ISSUE TITLE
请问，配置文件能给下么？

### ISSUE THREAD

**Issue by cc2017111** [AI-confused/CGEC-with-Pointer-Generator-Network-Bart#3]

**Comment by AI-confused** [comment]
😂抱歉，太久没关注issue了，配置文件在另一个更全面的仓库中
https://github.com/AI-confused/CCL2022_CGED-8_Top1_project/blob/main/Grammar_Error_Correct/Pointer-Generator-Net/config/grammar_ptr_train.yml
